### ISSUE TITLE
Deploy app to Heroku-dev & heroku-prod

### ISSUE THREAD

**Issue by Isalafont** [junkiesan/billie#13]
Create a heroku dev environnement and a heroku prod environnement 

It will be used to the CI - Pipeline

**Comment by junkiesan** [comment]
To push on the development branch please do: 
`git push development master`

And to push on production do: 
`git push heroku master`

For more information refer to [Billie's documentation](https://www.notion.so/Heroku-f105b4648b054f79b07ac03edc746efd)
